<?php

namespace Database\Seeders;

use App\Models\AturanPelanggaran;
use Illuminate\Database\Seeder;

class AturanPelanggaranSeeder extends Seeder
{
    public function run(): void
    {
        $sanksiUmum = [
            'sanksi_i' => 'Respons/pembinaan sesuai ketentuan sekolah.',
            'sanksi_ii' => 'Surat perjanjian/peringatan dan pembinaan sesuai tahap.',
            'sanksi_iii' => 'SP-2/SP-3, pemanggilan orang tua, dan pembinaan sesuai ketentuan.',
            'sanksi_iv' => 'Tahap tertinggi: dikembalikan ke orang tua bila ketentuan terpenuhi.',
        ];

        $aturan = [

            // =========================
            // RINGAN
            // =========================

            [
                'kode' => 'R001',
                'kategori' => 'Ringan',
                'subkategori' => 'Kedisiplinan & gadget',
                'nama' => 'Terlambat: terlambat masuk sekolah, terlambat mengerjakan tugas, mencontek atau melakukan kecurangan saat ujian.',
                'poin' => 5,
                'tahap_maksimal' => 4,
            ],
            [
                'kode' => 'R002',
                'kategori' => 'Ringan',
                'subkategori' => 'Kedisiplinan & gadget',
                'nama' => 'Tidak mengikuti kegiatan sekolah secara lengkap: upacara, apel sore, duquba, ibadah non-Islam, shalat berjamaah, keluar jam pelajaran tanpa izin.',
                'poin' => 5,
                'tahap_maksimal' => 4,
            ],
            [
                'kode' => 'R003',
                'kategori' => 'Ringan',
                'subkategori' => 'Kedisiplinan & gadget',
                'nama' => 'Memakai seragam tidak lengkap atau tidak sesuai ketentuan sekolah.',
                'poin' => 5,
                'tahap_maksimal' => 4,
            ],
            [
                'kode' => 'R004',
                'kategori' => 'Ringan',
                'subkategori' => 'Kedisiplinan & gadget',
                'nama' => 'Membawa kendaraan bermotor tanpa memenuhi ketentuan helm SNI, spion, plat nomor, knalpot standar, STNK, dan SIM bagi yang memiliki.',
                'poin' => 5,
                'tahap_maksimal' => 4,
            ],
            [
                'kode' => 'R005',
                'kategori' => 'Ringan',
                'subkategori' => 'Penampilan/grooming',
                'nama' => 'Memakai aksesoris yang tidak perlu dan tidak layak dipakai siswa.',
                'poin' => 3,
                'tahap_maksimal' => 4,
            ],
            [
                'kode' => 'R006',
                'kategori' => 'Ringan',
                'subkategori' => 'Penampilan/grooming',
                'nama' => 'Memakai make up dalam kegiatan pembelajaran harian, softlens bukan untuk kesehatan, melakukan skin alis, kuku panjang dicat/kutek, atau tato/menggambar kulit.',
                'poin' => 3,
                'tahap_maksimal' => 4,
            ],
            [
                'kode' => 'R007',
                'kategori' => 'Ringan',
                'subkategori' => 'Penampilan/grooming',
                'nama' => 'Rambut melebihi batas yang ditentukan bagi laki-laki: samping 2 cm, atas 3 cm, belakang 1 cm.',
                'poin' => 3,
                'tahap_maksimal' => 4,
            ],
            [
                'kode' => 'R008',
                'kategori' => 'Ringan',
                'subkategori' => 'Penampilan/grooming',
                'nama' => 'Mengubah warna rambut.',
                'poin' => 3,
                'tahap_maksimal' => 4,
            ],
            [
                'kode' => 'R009',
                'kategori' => 'Ringan',
                'subkategori' => 'Penampilan/grooming',
                'nama' => 'Berpenampilan tidak rapi: baju dikeluarkan selain seragam hari Kamis atau baju tidak dikancingkan.',
                'poin' => 3,
                'tahap_maksimal' => 4,
            ],
            [
                'kode' => 'R010',
                'kategori' => 'Ringan',
                'subkategori' => 'Penampilan/grooming',
                'nama' => 'Bau badan.',
                'poin' => 3,
                'tahap_maksimal' => 4,
            ],
            [
                'kode' => 'R011',
                'kategori' => 'Ringan',
                'subkategori' => 'Kedisiplinan & gadget',
                'nama' => 'Meminjam barang, nomor PIN, atau password orang lain tanpa izin pemilik.',
                'poin' => 5,
                'tahap_maksimal' => 4,
            ],
            [
                'kode' => 'R012',
                'kategori' => 'Ringan',
                'subkategori' => 'Kedisiplinan & gadget',
                'nama' => 'Bermain game online atau membuka media sosial/aplikasi hiburan saat KBM tanpa izin guru; menggunakan handphone saat KBM tanpa izin guru.',
                'poin' => 5,
                'tahap_maksimal' => 4,
            ],
            [
                'kode' => 'R013',
                'kategori' => 'Ringan',
                'subkategori' => 'Kedisiplinan & gadget',
                'nama' => 'Merekam atau memfoto kegiatan di dalam kelas tanpa izin guru untuk keperluan pribadi.',
                'poin' => 5,
                'tahap_maksimal' => 4,
            ],

            // =========================
            // SEDANG
            // =========================

            [
                'kode' => 'S001',
                'kategori' => 'Sedang',
                'subkategori' => 'Umum',
                'nama' => 'Tidak masuk sekolah tanpa keterangan yang jelas (alpa). Alpa dihitung per hari.',
                'poin' => 10,
                'tahap_maksimal' => 4,
            ],
            [
                'kode' => 'S002',
                'kategori' => 'Sedang',
                'subkategori' => 'Umum',
                'nama' => 'Berbicara tidak sopan, kasar atau berkonotasi negatif kepada sesama teman baik secara online atau offline.',
                'poin' => 10,
                'tahap_maksimal' => 4,
            ],
            [
                'kode' => 'S003',
                'kategori' => 'Sedang',
                'subkategori' => 'Umum',
                'nama' => 'Mengotori dan merusak lingkungan sekolah.',
                'poin' => 10,
                'tahap_maksimal' => 4,
            ],
            [
                'kode' => 'S004',
                'kategori' => 'Sedang',
                'subkategori' => 'Umum',
                'nama' => 'Tidak mengerjakan tugas yang diberikan oleh guru berkali-kali.',
                'poin' => 10,
                'tahap_maksimal' => 4,
            ],
            [
                'kode' => 'S005',
                'kategori' => 'Sedang',
                'subkategori' => 'Umum',
                'nama' => 'Berbohong kepada guru, termasuk tidak kembali saat izin, menggunakan HP orang tua untuk izin, berada di kantin saat pembelajaran, memalsukan surat dokter/orang tua, atau izin tanpa surat yang jelas.',
                'poin' => 10,
                'tahap_maksimal' => 4,
            ],
            [
                'kode' => 'S006',
                'kategori' => 'Sedang',
                'subkategori' => 'Umum',
                'nama' => 'Membuat kegaduhan/keributan di lingkungan sekolah.',
                'poin' => 10,
                'tahap_maksimal' => 4,
            ],
            [
                'kode' => 'S007',
                'kategori' => 'Sedang',
                'subkategori' => 'Umum',
                'nama' => 'Parkir atau menyimpan kendaraan di luar tempat yang disiapkan sekolah.',
                'poin' => 10,
                'tahap_maksimal' => 4,
            ],
            [
                'kode' => 'S008',
                'kategori' => 'Sedang',
                'subkategori' => 'Moral/digital/PPKSP',
                'nama' => 'Menyimpan dan menonton video porno.',
                'poin' => 15,
                'tahap_maksimal' => 4,
            ],
            [
                'kode' => 'S009',
                'kategori' => 'Sedang',
                'subkategori' => 'Umum',
                'nama' => 'Nongkrong menggunakan seragam sekolah di luar lingkungan sekolah.',
                'poin' => 10,
                'tahap_maksimal' => 4,
            ],
            [
                'kode' => 'S010',
                'kategori' => 'Sedang',
                'subkategori' => 'Moral/digital/PPKSP',
                'nama' => 'Berpacaran (kategori normal, sedang, berat).',
                'poin' => 15,
                'tahap_maksimal' => 4,
            ],
            [
                'kode' => 'S011',
                'kategori' => 'Sedang',
                'subkategori' => 'Moral/digital/PPKSP',
                'nama' => 'Berjudi secara langsung atau melakukan pinjaman online.',
                'poin' => 15,
                'tahap_maksimal' => 4,
            ],
            [
                'kode' => 'S012',
                'kategori' => 'Sedang',
                'subkategori' => 'Moral/digital/PPKSP',
                'nama' => 'Melakukan sikap/tindakan/perilaku yang menyinggung Suku, Agama, Ras, Antar Golongan (SARA).',
                'poin' => 15,
                'tahap_maksimal' => 4,
            ],
            [
                'kode' => 'S013',
                'kategori' => 'Sedang',
                'subkategori' => 'Moral/digital/PPKSP',
                'nama' => 'Menyalahgunakan uang yang dititipkan orang tua untuk sekolah atau mengambil barang dagangan dari pedagang yang mendukung/memfasilitasi pelanggaran tata tertib.',
                'poin' => 15,
                'tahap_maksimal' => 4,
            ],
            [
                'kode' => 'S014',
                'kategori' => 'Sedang',
                'subkategori' => 'Umum',
                'nama' => 'Melakukan siaran langsung/live streaming atau membuat konten joget, prank, challenge saat jam pelajaran, di lingkungan sekolah, atau menggunakan seragam/atribut sekolah untuk konten yang tidak pantas.',
                'poin' => 10,
                'tahap_maksimal' => 4,
            ],
            [
                'kode' => 'S015',
                'kategori' => 'Sedang',
                'subkategori' => 'Moral/digital/PPKSP',
                'nama' => 'Merekam atau memfoto guru maupun teman tanpa izin lalu menyebarkannya melalui media apa pun.',
                'poin' => 15,
                'tahap_maksimal' => 4,
            ],
            [
                'kode' => 'S016',
                'kategori' => 'Sedang',
                'subkategori' => 'Umum',
                'nama' => 'Menyebarkan berita bohong (hoaks), ujaran kebencian, atau provokasi melalui media sosial.',
                'poin' => 10,
                'tahap_maksimal' => 4,
            ],
            [
                'kode' => 'S017',
                'kategori' => 'Sedang',
                'subkategori' => 'Moral/digital/PPKSP',
                'nama' => 'Melakukan perundungan siber (cyberbullying): menghina, mengancam, atau mempermalukan orang lain melalui media digital.',
                'poin' => 15,
                'tahap_maksimal' => 4,
            ],
            [
                'kode' => 'S018',
                'kategori' => 'Sedang',
                'subkategori' => 'Umum',
                'nama' => 'Menyontek atau bekerja sama secara tidak jujur saat ulangan/ujian.',
                'poin' => 10,
                'tahap_maksimal' => 4,
            ],
            [
                'kode' => 'S019',
                'kategori' => 'Sedang',
                'subkategori' => 'Umum',
                'nama' => 'Menggunakan jasa joki tugas atau menyalahgunakan kecerdasan buatan (AI) untuk mengerjakan tugas/ujian dan mengakuinya sebagai karya sendiri.',
                'poin' => 10,
                'tahap_maksimal' => 4,
            ],
            [
                'kode' => 'S020',
                'kategori' => 'Sedang',
                'subkategori' => 'Moral/digital/PPKSP',
                'nama' => 'Menitipkan absen, memanipulasi presensi termasuk presensi digital, atau memalsukan surat izin/dispensasi.',
                'poin' => 15,
                'tahap_maksimal' => 4,
            ],
            [
                'kode' => 'S021',
                'kategori' => 'Sedang',
                'subkategori' => 'Moral/digital/PPKSP',
                'nama' => 'Melakukan tindakan intoleransi atau diskriminasi terhadap warga sekolah berdasarkan suku, agama, ras, golongan, fisik, atau kondisi tertentu termasuk body shaming.',
                'poin' => 15,
                'tahap_maksimal' => 4,
            ],

            // =========================
            // BERAT
            // =========================

            [
                'kode' => 'B001',
                'kategori' => 'Berat',
                'subkategori' => 'Eskalasi 4 tahap',
                'nama' => 'Mencemarkan nama baik pimpinan sekolah, guru atau almamater; mengucapkan kata-kata kebencian, kasar atau kotor langsung/melalui media sosial; atau tidak menghormati dan tidak memuliakan guru.',
                'poin' => 25,
                'tahap_maksimal' => 4,
            ],
            [
                'kode' => 'B002',
                'kategori' => 'Berat',
                'subkategori' => 'Eskalasi 3 tahap',
                'nama' => 'Terbukti merokok di dalam atau luar lingkungan sekolah.',
                'poin' => 35,
                'tahap_maksimal' => 3,
            ],
            [
                'kode' => 'B003',
                'kategori' => 'Berat',
                'subkategori' => 'Eskalasi 3 tahap',
                'nama' => 'Terbukti mengkonsumsi minum-minuman keras.',
                'poin' => 35,
                'tahap_maksimal' => 3,
            ],
            [
                'kode' => 'B004',
                'kategori' => 'Berat',
                'subkategori' => 'Eskalasi 2 tahap',
                'nama' => 'Membawa senjata tajam dan api ke sekolah.',
                'poin' => 50,
                'tahap_maksimal' => 2,
            ],
            [
                'kode' => 'B005',
                'kategori' => 'Berat',
                'subkategori' => 'Eskalasi 2 tahap',
                'nama' => 'Terbukti melakukan kekerasan, pemukulan, pemalakan, atau ancaman di dalam dan luar lingkungan sekolah.',
                'poin' => 50,
                'tahap_maksimal' => 2,
            ],
            [
                'kode' => 'B006',
                'kategori' => 'Berat',
                'subkategori' => 'Eskalasi 3 tahap',
                'nama' => 'Melakukan perkelahian di dalam dan luar lingkungan sekolah.',
                'poin' => 35,
                'tahap_maksimal' => 3,
            ],
            [
                'kode' => 'B007',
                'kategori' => 'Berat',
                'subkategori' => 'Eskalasi 3 tahap',
                'nama' => 'Melakukan vandalisme, yakni merusak fasilitas sekolah atau coret-coret meja dan bangku.',
                'poin' => 35,
                'tahap_maksimal' => 3,
            ],
            [
                'kode' => 'B008',
                'kategori' => 'Berat',
                'subkategori' => 'Eskalasi 3 tahap',
                'nama' => 'Mencuri dengan sengaja barang milik sekolah atau barang milik orang lain.',
                'poin' => 35,
                'tahap_maksimal' => 3,
            ],
            [
                'kode' => 'B009',
                'kategori' => 'Berat',
                'subkategori' => 'Eskalasi 3 tahap',
                'nama' => 'Memalsukan tanda tangan.',
                'poin' => 35,
                'tahap_maksimal' => 3,
            ],
            [
                'kode' => 'B010',
                'kategori' => 'Berat',
                'subkategori' => 'Eskalasi 2 tahap',
                'nama' => 'Melakukan seks bebas, pergaulan bebas dan perilaku menyimpang.',
                'poin' => 50,
                'tahap_maksimal' => 2,
            ],
            [
                'kode' => 'B011',
                'kategori' => 'Berat',
                'subkategori' => 'Eskalasi 3 tahap',
                'nama' => 'Berjudi secara langsung maupun melalui media sosial (judi online).',
                'poin' => 35,
                'tahap_maksimal' => 3,
            ],
            [
                'kode' => 'B012',
                'kategori' => 'Berat',
                'subkategori' => 'Eskalasi 3 tahap',
                'nama' => 'Menggelapkan uang sekolah atau perusahaan tempat PKL.',
                'poin' => 35,
                'tahap_maksimal' => 3,
            ],
            [
                'kode' => 'B013',
                'kategori' => 'Berat',
                'subkategori' => 'Eskalasi 2 tahap',
                'nama' => 'Melakukan tindakan asusila atau perilaku seksual dan penyimpangan.',
                'poin' => 50,
                'tahap_maksimal' => 2,
            ],
            [
                'kode' => 'B014',
                'kategori' => 'Berat',
                'subkategori' => 'Eskalasi 3 tahap',
                'nama' => 'Terbukti menggunakan rokok elektrik (vape/pod) di dalam atau luar lingkungan sekolah.',
                'poin' => 35,
                'tahap_maksimal' => 3,
            ],
            [
                'kode' => 'B015',
                'kategori' => 'Berat',
                'subkategori' => 'Eskalasi 3 tahap',
                'nama' => 'Menyalahgunakan obat-obatan keras/obat bebas di luar ketentuan medis atau menghirup zat adiktif (ngelem/inhalan).',
                'poin' => 35,
                'tahap_maksimal' => 3,
            ],
            [
                'kode' => 'B016',
                'kategori' => 'Berat',
                'subkategori' => 'Eskalasi 4 tahap',
                'nama' => 'Mengunggah atau menyebarkan konten yang mencemarkan nama baik sekolah, pimpinan, atau guru melalui media sosial.',
                'poin' => 25,
                'tahap_maksimal' => 4,
            ],
            [
                'kode' => 'B017',
                'kategori' => 'Berat',
                'subkategori' => 'Eskalasi 3 tahap',
                'nama' => 'Membuat akun palsu/menyamar sebagai orang lain (impersonasi) atau menyebarkan data pribadi orang lain (doxing) untuk merugikan.',
                'poin' => 35,
                'tahap_maksimal' => 3,
            ],
            [
                'kode' => 'B018',
                'kategori' => 'Berat',
                'subkategori' => 'Eskalasi 2 tahap',
                'nama' => 'Memproduksi, meminta, atau menyebarkan konten intim/asusila antar pelajar, termasuk melalui media digital.',
                'poin' => 50,
                'tahap_maksimal' => 2,
            ],
            [
                'kode' => 'B019',
                'kategori' => 'Berat',
                'subkategori' => 'Eskalasi 3 tahap',
                'nama' => 'Menjadi pelaku penipuan termasuk penipuan online atau menyalahgunakan identitas orang lain untuk memperoleh keuntungan.',
                'poin' => 35,
                'tahap_maksimal' => 3,
            ],
            [
                'kode' => 'B020',
                'kategori' => 'Berat',
                'subkategori' => 'Eskalasi 2 tahap',
                'nama' => 'Melakukan pelecehan atau kekerasan seksual terhadap sesama warga sekolah, verbal, non-verbal, fisik, maupun melalui media digital.',
                'poin' => 50,
                'tahap_maksimal' => 2,
            ],
            [
                'kode' => 'B021',
                'kategori' => 'Berat',
                'subkategori' => 'Eskalasi 2 tahap',
                'nama' => 'Terlibat dalam penyebaran paham atau kegiatan radikalisme/ekstremisme dan intoleransi yang berbasis kekerasan.',
                'poin' => 50,
                'tahap_maksimal' => 2,
            ],

            // =========================
            // LUAR BIASA
            // =========================

            [
                'kode' => 'LB001',
                'kategori' => 'Luar Biasa',
                'subkategori' => 'Semua',
                'nama' => 'Merencanakan, mendukung, ikut serta, bahkan menonton dalam kegiatan tawuran.',
                'poin' => 100,
                'tahap_maksimal' => 1,
                'sanksi_i' => 'Dikembalikan ke orang tua.',
                'sanksi_ii' => null,
                'sanksi_iii' => null,
                'sanksi_iv' => null,
                'langsung_kembali' => true,
            ],
            [
                'kode' => 'LB002',
                'kategori' => 'Luar Biasa',
                'subkategori' => 'Semua',
                'nama' => 'Mengonsumsi dan mengedarkan narkoba.',
                'poin' => 100,
                'tahap_maksimal' => 1,
                'sanksi_i' => 'Dikembalikan ke orang tua.',
                'sanksi_ii' => null,
                'sanksi_iii' => null,
                'sanksi_iv' => null,
                'langsung_kembali' => true,
            ],
            [
                'kode' => 'LB003',
                'kategori' => 'Luar Biasa',
                'subkategori' => 'Semua',
                'nama' => 'Melakukan tindakan kriminal yang dibuktikan dengan catatan kepolisian.',
                'poin' => 100,
                'tahap_maksimal' => 1,
                'sanksi_i' => 'Dikembalikan ke orang tua.',
                'sanksi_ii' => null,
                'sanksi_iii' => null,
                'sanksi_iv' => null,
                'langsung_kembali' => true,
            ],
            [
                'kode' => 'LB004',
                'kategori' => 'Luar Biasa',
                'subkategori' => 'Semua',
                'nama' => 'Melakukan perundungan/perilaku menyakiti orang lain, disengaja maupun berulang (bullying), yang mengakibatkan dampak fatal.',
                'poin' => 100,
                'tahap_maksimal' => 1,
                'sanksi_i' => 'Dikembalikan ke orang tua.',
                'sanksi_ii' => null,
                'sanksi_iii' => null,
                'sanksi_iv' => null,
                'langsung_kembali' => true,
            ],
            [
                'kode' => 'LB005',
                'kategori' => 'Luar Biasa',
                'subkategori' => 'Semua',
                'nama' => 'Terbukti hamil atau menghamili.',
                'poin' => 100,
                'tahap_maksimal' => 1,
                'sanksi_i' => 'Dikembalikan ke orang tua.',
                'sanksi_ii' => null,
                'sanksi_iii' => null,
                'sanksi_iv' => null,
                'langsung_kembali' => true,
            ],
            [
                'kode' => 'LB006',
                'kategori' => 'Luar Biasa',
                'subkategori' => 'Semua',
                'nama' => 'Melakukan kekerasan fisik terhadap guru.',
                'poin' => 100,
                'tahap_maksimal' => 1,
                'sanksi_i' => 'Dikembalikan ke orang tua.',
                'sanksi_ii' => null,
                'sanksi_iii' => null,
                'sanksi_iv' => null,
                'langsung_kembali' => true,
            ],
            [
                'kode' => 'LB007',
                'kategori' => 'Luar Biasa',
                'subkategori' => 'Semua',
                'nama' => 'Menikah dalam status murid.',
                'poin' => 100,
                'tahap_maksimal' => 1,
                'sanksi_i' => 'Dikembalikan ke orang tua.',
                'sanksi_ii' => null,
                'sanksi_iii' => null,
                'sanksi_iv' => null,
                'langsung_kembali' => true,
            ],
        ];

        foreach ($aturan as $item) {
            $data = array_merge($sanksiUmum, [
                'langsung_kembali' => false,
                'aktif' => true,
            ], $item);

            AturanPelanggaran::updateOrCreate(
                ['kode' => $data['kode']],
                $data
            );
        }
    }
}
